In [1]:
!pip3 -q install --upgrade google-cloud-documentai google-cloud-storage google-cloud-documentai-toolbox

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-python-client 1.8.0 requires google-api-core<2dev,>=1.13.0, but you have google-api-core 2.21.0 which is incompatible.

# OCR Parser

In [6]:
from google.api_core.client_options import ClientOptions
from google.cloud import documentai


PROJECT_ID = ""
LOCATION = "us"  # Format is 'us' or 'eu'
PROCESSOR_ID = ""

# The local file in your current working directory
FILE_PATH = "data/naf23mini.pdf"
# Refer to https://cloud.google.com/document-ai/docs/file-types
# for supported file types
MIME_TYPE = "application/pdf"

In [7]:
# Instantiates a client
docai_client = documentai.DocumentProcessorServiceClient(
    client_options=ClientOptions(api_endpoint=f"{LOCATION}-documentai.googleapis.com")
)

In [8]:
# The full resource name of the processor, e.g.:
# projects/project-id/locations/location/processor/processor-id
# You must create new processors in the Cloud Console first
RESOURCE_NAME = docai_client.processor_path(PROJECT_ID, LOCATION, PROCESSOR_ID)

In [11]:
# Read the file into memory
with open(FILE_PATH, "rb") as image:
    image_content = image.read()

# Load Binary Data into Document AI RawDocument Object
raw_document = documentai.RawDocument(content=image_content, mime_type=MIME_TYPE)

# Configure the process request
request = documentai.ProcessRequest(name=RESOURCE_NAME, raw_document=raw_document)

# Use the Document AI client to process the sample form
result = docai_client.process_document(request=request)

document_object = result.document
print("Document processing complete.")
print(f"Text: {document_object.text}")

In [10]:
type(result)

google.cloud.documentai_v1.types.document_processor_service.ProcessResponse

In [12]:
type(document_object)

google.cloud.documentai_v1.types.document.Document

In [17]:
# document_object

In [26]:
print(document_object.text)

National Ataxia Foundation
Table of Contents
December 31, 2023 and 2022
Page No.
3
Independent Auditor's Report
Financial Statements
Statements of Financial Position
Statements of Activities
Statements of Functional Expenses
Statements of Cash Flows
Notes to the Financial Statements
2
160
7
9
11
12
Assets
Current Assets
Cash and cash equivalents
Accounts receivable
Prepaid expenses
Total Current Assets
Noncurrent Assets
Right-of-use asset
Investments
Total Noncurrent Assets
Total Assets
Liabilities and Net Assets
Current Liabilities
Accounts payable
National Ataxia Foundation
Statements of Financial Position
December 31, 2023 and 2022
2023
2022
$ 1,008,716
6,438
255,729
$ 1,969,164
55,331
187,070
1,270,883
2,211,565
57,320
89,034
2,788,623
2,707,996
2,845,943
2,797,030
$ 4,116,826 $ 5,008,595
$
298,827 $ 440,809
Accrued payroll and related expenses
35,140
29,226
Deferred revenue
109,810
22,291
Operating lease liability, current portion
32,750
31,548
Total Current Liabilities
476,527
523,874
Long-term Operating Lease Liability, Less Current Portion
25,353
58,104
Total Liabilities
501,880
581,978
Net Assets
Without donor restriction
Board designated - operating reserve
Undesignated
Total Net Assets Without Donor Restriction
With donor restriction
Total Net Assets
Total Liabilities and Net Assets
See Independent Auditor's Report and Notes to the Financial Statements.
6
396,499
420,985
537,880
1,963,826
934,379
2,384,811
2,680,567
2,041,806
3,614,946
4,426,617
$ 4,116,826
$ 5,008,595
National Ataxia Foundation
Statements of Functional Expenses
For the Years Ended December 31, 2023 and 2022
Program Services
2023
Supporting Services
Education
Research
and Service
Drug
Development
Collaborative
Total Program
Services
Management
and General
Fundraising
Total
Payroll taxes
Fringe benefits
Salaries and Related Expenses
Salaries and wages
Total Salaries and Related Expenses
$
494,104
$ 362,830
$ 162,033
38,208
27,159
12,319
45,455
52,132
13,763
$ 1,018,967
77,686
111,350
$
138,082
9,732
$ 293,427
21,710
$ 1,450,476
109,128
21,428
39,024
171,802
577,767
442,121
188,115
1,208,003
169,242
354,161
1,731,406
Insurance
Bank and credit card fees
Development
Dues and subscriptions
Meeting expense
1,332
3,592
4,924
43,689
48,613
975
5,833
43
1,018
2,859
500
4,377
2,273
8,106
22,422
49,882
80,410
12,931
12,931
168,589
521,241
969
690,799
44,865
79,814
815,478
Miscellaneous
140
3,500
3,640
143
1,228
5,011
Occupancy
63,895
63,895
Office expense
2,286
1,690
4,913
8,889
31,985
10,276
51,150
Printing, marketing and multimedia
15,155
Professional services
61,747
118,687
27,313
133,842
45,852
29,898
209,592
Research grants
740,530
12,140
982,290
101,200
100,196
22,859
224,255
Support grants
26,520
1,722,820
26,520
1,722,820
26,520
Total Expenses
$ 1,574,354
$ 1,146,980
$ 1,188,427
$ 3,909,761
$ 538,079
$ 548,618
$ 4,996,458
See Independent Auditor's Report and Notes to the Financial Statements.
9
National Ataxia Foundation
Notes to the Financial Statements
December 31, 2023 and 2022
Note 1: Summary of Significant Accounting Policies
A. Nature of Activities
National Ataxia Foundation (the Foundation) was incorporated as a Minnesota nonprofit corporation in 1957. The
Foundation's mission is to accelerate the development of treatments and a cure while working to improve the lives of
those living with Ataxia.
To further the mission, the Foundation provides services in the following program areas:
Education and Service
Increased awareness about hereditary and sporadic ataxia disorders is promoted through a variety of education
programs and materials for ataxia families, researchers, physicians, allied health professionals, government agencies,
legislative officials and the general public. The Foundation publishes Generations, an annual newsletter and a monthly
e-newsletter devoted to ataxia related articles including the latest research and other information beneficial to
individuals with ataxia. The Foundation also offers several webinars throughout the year on current topics relevant to
the ataxia community. Other educational materials, such as books, videos and fact sheets are provided to persons
with ataxia, family members and health care professionals on a "direct request" basis through the NAF office. The
Foundation's advocacy activities, such as Hill Days, serve to raise awareness about ataxia and policy issues
impacting the ataxia community. The annual ataxia conference, and sponsorship and/or participation in national and
international meetings, symposiums and seminars also serve to increase ataxia awareness.
The National Ataxia Foundation attempts to locate people and families with hereditary and sporadic ataxia in order to
provide them with information about ataxia. This is accomplished by providing updated information about ataxia to
the general public by maintaining a website, social media channels, newsletters, and webinars. The Foundation
assists individuals and families by identifying clinical resources and making appropriate referrals for neurological
care, genetic counseling and gene testing. The Foundation also assists people with locating resources within their
own communities, including support groups. The Foundation's network of support groups throughout the country
provides families with access to in-person and virtual meeting opportunities.
Research
NAF is committed to funding cutting-edge basic and translational research into hereditary and sporadic ataxia. The
goals of NAF's research program are to further elucidate the disease mechanisms of ataxias, bring early-career
clinicians and scientists into ataxia research, and help drive the field towards developing treatments and a cure for
ataxia. Annual grants are selected through a competitive review process that includes NAF's Medical and Research
Advisory Board members and over 80 leading ataxia scientists and clinicians, both domestic and international.
Each year NAF awards grants to researchers from domestic and international non-profit and for-profit institutions that
directly support basic and translational ataxia research through the following funding mechanisms:
1. Pioneer SCA3 Translational Research Awards: Annually granted to outstanding research proposals that aim
to make significant advancements in the development of treatments and/or improvements to patient care for
Spinocerebellar Ataxia Type 3 (SCA3). Proposals may incorporate other forms of ataxia but must have a
predominant focus on SCA3 translational or clinical research.
2. Seed Money Research Grant: Granted primarily as "seed monies" to assist investigators in the early or pilot
phase of their studies and as additional support for ongoing investigations on demonstration of need. It is
hoped that these studies will be further developed to attract future funding from other sources.
3. Early Career Investigator Award: The Early Career Investigator Award was created to encourage early career
clinical and scientific investigators to pursue a career in the field of ataxia research.
12

In [28]:
document_object.chunked_document

In [30]:
for page in document_object.pages:
    print(page.page_number)
    print(f"\nFound {len(page.tables)} table(s):")

1

Found 0 table(s):
2

Found 0 table(s):
3

Found 0 table(s):
4

Found 0 table(s):

# Form Parser

In [31]:
from google.api_core.client_options import ClientOptions
from google.cloud import documentai
from os.path import splitext
from typing import List, Sequence
from google.cloud import documentai
import pandas as pd


PROJECT_ID = 
LOCATION = "us"  # Format is 'us' or 'eu'
PROCESSOR_ID = 

# The local file in your current working directory
FILE_PATH = "data/naf23mini.pdf"
# Refer to https://cloud.google.com/document-ai/docs/file-types
# for supported file types
MIME_TYPE = "application/pdf"

In [34]:
def online_process(
    project_id: str,
    location: str,
    processor_id: str,
    file_path: str,
    mime_type: str,
) -> documentai.Document:
    """
    Processes a document using the Document AI Online Processing API.
    """

    opts = {"api_endpoint": f"{location}-documentai.googleapis.com"}

    # Instantiates a client
    documentai_client = documentai.DocumentProcessorServiceClient(client_options=opts)

    # The full resource name of the processor, e.g.:
    # projects/project-id/locations/location/processor/processor-id
    # You must create new processors in the Cloud Console first
    resource_name = documentai_client.processor_path(project_id, location, processor_id)

    # Read the file into memory
    with open(file_path, "rb") as image:
        image_content = image.read()

        # Load Binary Data into Document AI RawDocument Object
        raw_document = documentai.RawDocument(
            content=image_content, mime_type=mime_type
        )

        # Configure the process request
        request = documentai.ProcessRequest(
            name=resource_name, raw_document=raw_document
        )

        # Use the Document AI client to process the sample form
        result = documentai_client.process_document(request=request)

        return result.document
    
document = online_process(
    project_id=PROJECT_ID,
    location=LOCATION,
    processor_id=PROCESSOR_ID,
    file_path=FILE_PATH,
    mime_type=MIME_TYPE,
)

In [52]:
def get_table_data(
    rows: Sequence[documentai.Document.Page.Table.TableRow], text: str
) -> List[List[str]]:
    """
    Get Text data from table rows
    """
    all_values: List[List[str]] = []
    for row in rows:
        current_row_values: List[str] = []
        for cell in row.cells:
            current_row_values.append(
                text_anchor_to_text(cell.layout.text_anchor, text)
            )
        all_values.append(current_row_values)
    return all_values

def text_anchor_to_text(text_anchor: documentai.Document.TextAnchor, text: str) -> str:
    """
    Document AI identifies table data by their offsets in the entirity of the
    document's text. This function converts offsets to a string.
    """
    response = ""
    # If a text segment spans several lines, it will
    # be stored in different text segments.
    for segment in text_anchor.text_segments:
        start_index = int(segment.start_index)
        end_index = int(segment.end_index)
        response += text[start_index:end_index]
    return response.strip().replace("\n", " ")

In [55]:
for page in document.pages:
    print(len(page.tables), 'tables found' )
    
    # if len(page.tables)==0:
        # print(page.tokens)
    # print(page.page_number)
    for index, table in enumerate(page.tables):
        header_row_values = get_table_data(table.header_rows, document.text)
        body_row_values = get_table_data(table.body_rows, document.text)
        
        df = pd.DataFrame(
            data=body_row_values,
            columns=pd.MultiIndex.from_arrays(header_row_values),
        )
        print(f"Page {page.page_number} - Table {index}")
        display(df)
        print(header_row_values)

0 tables found
5 tables found
Page 2 - Table 0

                            Total Liabilities          501,880 581,978
0        Net Assets Without donor restriction
1        Board designated - operating reserve          396,499 420,985
2                                Undesignated        537,880 1,963,826
3  Total Net Assets Without Donor Restriction        934,379 2,384,811
4                      With donor restriction      2,680,567 2,041,806
5                            Total Net Assets      3,614,946 4,426,617
6            Total Liabilities and Net Assets  $ 4,116,826 $ 5,008,595

[['Total Liabilities', '501,880 581,978']]
Page 2 - Table 1

  Cash and cash equivalents $ 1,008,716 $ 1,969,164
0       Accounts receivable       6,438      55,331
1          Prepaid expenses     255,729     187,070
2      Total Current Assets   1,270,883   2,211,565

[['Cash and cash equivalents', '$ 1,008,716', '$ 1,969,164']]
Page 2 - Table 2

,,2023 2022
0,Assets,
1,Current Assets,
2,Cash and cash equivalents,"$ 1,008,716 $ 1,969,164"
3,Accounts receivable,"6,438 55,331"
4,Prepaid expenses,"255,729 187,070"
5,Total Current Assets,"1,270,883 2,211,565"
6,Noncurrent Assets,
7,Right-of-use asset Investments,"89,034 57,320 2,788,623 2,707,996"
8,Total Noncurrent Assets,"2,845,943 2,797,030"
9,Total Assets,"$ 4,116,826 $ 5,008,595"
10,Liabilities and Net Assets Current Liabilities,
11,Accounts payable,"$ 298,827 $ 440,809"
12,Accrued payroll and related expenses,"35,140 29,226"
13,Deferred revenue,"109,810 22,291"
14,"Operating lease liability, current portion","32,750 31,548"
15,Total Current Liabilities,"523,874 476,527"
16,"Long-term Operating Lease Liability, Less Curr...","25,353 58,104"
17,Total Liabilities,"501,880 581,978"
18,Net Assets,

[['', '2023 2022']]
Page 2 - Table 3

                             Accounts payable $ 298,827 $ 440,809
0        Accrued payroll and related expenses       35,140 29,226
1                            Deferred revenue      109,810 22,291
2  Operating lease liability, current portion       32,750 31,548
3                   Total Current Liabilities     523,874 476,527

[['Accounts payable', '$ 298,827 $ 440,809']]
Page 2 - Table 4

      57,320     89,034
0  2,788,623  2,707,996
1  2,845,943  2,797,030

[['57,320', '89,034']]
3 tables found
Page 3 - Table 0

,"3,592 1,332 Bank and credit card fees",,"4,924","43,689","48,613"
0,975 43 Development,,"1,018","2,859","500 4,377"
1,"5,833 2,273 Dues and subscriptions",,"8,106","22,422","49,882 80,410"
2,"168,589 521,241 Insurance Meeting expense",969,"690,799","12,931 44,865","79,814 12,931 815,478"
3,"3,500 140 Miscellaneous",,"3,640",143,"1,228 5,011"
4,"Occupancy Office expense 2,286 1,690","4,913","8,889","63,895 31,985","63,895 51,150 10,276"
5,"Printing, marketing and multimedia 118,687 15,155",,"133,842","45,852","209,592 29,898"
6,"Professional services 27,313 61,747","12,140","101,200","100,196","224,255 22,859"
7,"Research grants Support grants 740,530 26,520 ...","982,290 $ 1,188,427 $","1,722,820 26,520 $ 3,909,761","538,079","1,722,820 26,520 $ 548,618 $ 4,996,458"

[['3,592 1,332 Bank and credit card fees', '', '4,924', '43,689', '48,613']]
Page 3 - Table 1

,Research,Education and Service,Drug Development Collaborative,Total Program Services,Management and General,Fundraising,Total
0,"$ 494,104","$ 362,830","$ 162,033","$ 1,018,967","$ 138,082","$ 293,427","$ 1,450,476"
1,"38,208","27,159","12,319","77,686","9,732","21,710","109,128"
2,"45,455","52,132","13,763","111,350","21,428","39,024","171,802"
3,"577,767","442,121","188,115","1,208,003","169,242","354,161","1,731,406"
4,"1,332","3,592",,"4,924","43,689",,"48,613"

[['Research', 'Education and Service', 'Drug Development Collaborative', 'Total Program Services', 'Management and General', 'Fundraising', 'Total']]
Page 3 - Table 2

                    Salaries and wages $ 494,104 $ 362,830 $ 162,033 $
0                        Payroll taxes    38,208    27,159    12,319
1                      Fringe benefits    45,455    52,132    13,763
2  Total Salaries and Related Expenses   577,767   442,121   188,115

[['Salaries and wages', '$ 494,104', '$ 362,830', '$ 162,033', '$']]
0 tables found